[#ftl]
[#include "../formMacros.ftl"]

[@rowBreak/]
[@modalContainer]
    [@datepicker "addIesire-form-dataIesirii" "dataIesirii" "REGISTRU.DATA_IESIRII" "DATA.PLACEHOLDER" "6"/]
    [@input "addIesire-form-rezolvare" "rezolvare" "REGISTRU.REZOLVARE" "REGISTRU.REZOLVARE.PLACEHOLDER" "" "6"/]
    [@elementWithLink "modal-addDestinatar" "ADD_DESTINATAR" "6"]
        [@embedableSelectBox "addIesire-form-catreCineSALucrat" "catreCineSALucrat" "REGISTRU.CATRE_CINE_S_A_LUCRAT" "SELECT.PLACEHOLDER" "SEARCH.NO_RESULTS" ] [/@embedableSelectBox]
    [/@elementWithLink]
    [@input "addIesire-form-nrDosarSiAn" "nrDosarSiAn" "REGISTRU.NR_DOSAR_SI_AN" "REGISTRU.NR_DOSAR_SI_AN.PLACEHOLDER" "" "6"/]
    [@rowBreak/]
    [@elementWithLink "modal-addIntrare" "BUT_ADD_INTRARE" "6"]
        [@embedableSelectBox "addIesire-form-dataSiNrDeIntrare" "dataSiNrDeIntrare" "REGISTRU.DATA_SI_NR_INTRARE" "SELECT.PLACEHOLDER" "SEARCH.NO_RESULTS" /]
    [/@elementWithLink]
    [@input "addIesire-form-nrSiDataRevenirii" "nrSiDataRevenirii" "REGISTRU.NR_SI_DATA_REVENIRE" "REGISTRU.NR_SI_DATA_REVENIRE.PLACEHOLDER" "" "6"/]
    [@checkbox "addIesire-form-formatFizic" "formatFizic" "REGISTRU.PRIMIT_PRIN_POSTA_FORM" "" "6"/]
[/@modalContainer]
