[#ftl]
[#include "../formMacros.ftl"]

[@rowBreak/]
[@modalContainer]
    [@hiddenInput "userProfile-form-id-profil" "id-profil"/]
    [@adminInput "userProfile-form-nume" "nume" "USER.LASTNAME" "USER.LASTNAME.PLACEHOLDER" "" "4"/]
    [@adminInput "userProfile-form-prenume" "prenume" "USER.NAME" "USER.NAME.PLACEHOLDER" "" "4"/]
    [@elementWithLink "modal-changePassword" "SCHIMBA_PAROLA" "4"]
        [@embedableAdminInput "userProfile-form-username" "username" "USER.USERNAME" ""/]
    [/@elementWithLink]
    [@adminInput "userProfile-form-email" "email" "USER.EMAIL" "USER.EMAIL.PLACEHOLDER" "" "6"/]
    [@adminInput "userProfile-form-workTel" "workTel" "USER.WORKPHONE" "USER.PHONE.PLACEHOLDER" "" "6"/]
    [@adminInput "userProfile-form-tel" "tel" "USER.MOBILEPHONE" "USER.PHONE.PLACEHOLDER" "" "6"/]
    [@adminInput "userProfile-form-fax" "fax" "USER.FAX" "USER.PHONE.PLACEHOLDER" "" "6"/]
[/@modalContainer]
